# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.18.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.18.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jaydon/CLionProjects/milestone1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jaydon/CLionProjects/milestone1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.18.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.18.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jaydon/CLionProjects/milestone1/CMakeFiles /Users/jaydon/CLionProjects/milestone1//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jaydon/CLionProjects/milestone1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named milestone1

# Build rule for target.
milestone1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 milestone1
.PHONY : milestone1

# fast build rule for target.
milestone1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milestone1.dir/build.make CMakeFiles/milestone1.dir/build
.PHONY : milestone1/fast

Agent.o: Agent.cpp.o

.PHONY : Agent.o

# target to build an object file
Agent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milestone1.dir/build.make CMakeFiles/milestone1.dir/Agent.cpp.o
.PHONY : Agent.cpp.o

Agent.i: Agent.cpp.i

.PHONY : Agent.i

# target to preprocess a source file
Agent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milestone1.dir/build.make CMakeFiles/milestone1.dir/Agent.cpp.i
.PHONY : Agent.cpp.i

Agent.s: Agent.cpp.s

.PHONY : Agent.s

# target to generate assembly for a file
Agent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milestone1.dir/build.make CMakeFiles/milestone1.dir/Agent.cpp.s
.PHONY : Agent.cpp.s

Main.o: Main.cpp.o

.PHONY : Main.o

# target to build an object file
Main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milestone1.dir/build.make CMakeFiles/milestone1.dir/Main.cpp.o
.PHONY : Main.cpp.o

Main.i: Main.cpp.i

.PHONY : Main.i

# target to preprocess a source file
Main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milestone1.dir/build.make CMakeFiles/milestone1.dir/Main.cpp.i
.PHONY : Main.cpp.i

Main.s: Main.cpp.s

.PHONY : Main.s

# target to generate assembly for a file
Main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milestone1.dir/build.make CMakeFiles/milestone1.dir/Main.cpp.s
.PHONY : Main.cpp.s

World.o: World.cpp.o

.PHONY : World.o

# target to build an object file
World.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milestone1.dir/build.make CMakeFiles/milestone1.dir/World.cpp.o
.PHONY : World.cpp.o

World.i: World.cpp.i

.PHONY : World.i

# target to preprocess a source file
World.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milestone1.dir/build.make CMakeFiles/milestone1.dir/World.cpp.i
.PHONY : World.cpp.i

World.s: World.cpp.s

.PHONY : World.s

# target to generate assembly for a file
World.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milestone1.dir/build.make CMakeFiles/milestone1.dir/World.cpp.s
.PHONY : World.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... milestone1"
	@echo "... Agent.o"
	@echo "... Agent.i"
	@echo "... Agent.s"
	@echo "... Main.o"
	@echo "... Main.i"
	@echo "... Main.s"
	@echo "... World.o"
	@echo "... World.i"
	@echo "... World.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

